### ISSUE TITLE
npm start 启动报错了

### ISSUE THREAD

**Issue by shichunlei** [jsososo/QQMusicApi#104]
> qqmusicapi@0.0.0 start /home/cells/RailsProjects/QQMusicApi
> node ./bin/www

/home/cells/RailsProjects/QQMusicApi/app.js:60
        ...req.query,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cells/RailsProjects/QQMusicApi/bin/www:7:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qqmusicapi@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the qqmusicapi@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cells/.npm/_logs/2021-02-28T04_29_23_214Z-debug.log

**Comment by jsososo** [comment]
node 版本太低了，我本地用的是 12.8.3
