### ISSUE TITLE
歌手相关接口无法使用

### ISSUE THREAD

**Issue by QuXiang-code** [jsososo/QQMusicApi#137]
一请求歌手的简介、歌手歌曲等接口，服务自动停止，信息如下

C:\Users\30710\Desktop\QQMusicApi\routes\singer.js:131
    let cacheData = cache.get(cacheKey)
                          ^

TypeError: Cannot read properties of undefined (reading 'get')
    at /songs (C:\Users\30710\Desktop\QQMusicApi\routes\singer.js:131:27)
    at C:\Users\30710\Desktop\QQMusicApi\app.js:63:37
    at Layer.handle [as handle_request] (C:\Users\30710\Desktop\QQMusicApi\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\30710\Desktop\QQMusicApi\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\30710\Desktop\QQMusicApi\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\30710\Desktop\QQMusicApi\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\30710\Desktop\QQMusicApi\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\30710\Desktop\QQMusicApi\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\30710\Desktop\QQMusicApi\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\30710\Desktop\QQMusicApi\node_modules\express\lib\router\index.js:174:3)

**Comment by DIPENG-XU** [comment]
这应该是企鹅那边重新设置了一些东西，好像好几个Github的QQ音乐项目都出问题了

**Comment by jsososo** [comment]
最新版已修复
