### ISSUE TITLE
歌手介绍接口错误

### ISSUE THREAD

**Issue by a13087635768** [jsososo/QQMusicApi#138]
![image](https://user-images.githubusercontent.com/23163284/151612193-ad2bf749-00f3-4cd4-ad82-8aa76fda9cb4.png)
获取歌手的信息时出错
有空时候修复一下吧
url： /singer/desc

[0mGET /singer/desc?singermid=001JDzPT3JdvqK [0m- [0m- ms - -[0m
(node:13) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
at /desc (/home/qqmusic/routes/singer.js:10:27)
at /home/qqmusic/app.js:63:37
at Layer.handle [as handle_request] (/home/qqmusic/node_modules/express/lib/router/layer.js:95:5)
at next (/home/qqmusic/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/home/qqmusic/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/home/qqmusic/node_modules/express/lib/router/layer.js:95:5)
at /home/qqmusic/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/home/qqmusic/node_modules/express/lib/router/index.js:335:12)
at next (/home/qqmusic/node_modules/express/lib/router/index.js:275:10)

**Comment by jsososo** [comment]
最新版已修复
