### ISSUE TITLE
search接口 系统异常：Request failed with status code 404

### ISSUE THREAD

**Issue by CaptainRuby** [jsososo/QQMusicApi#181]
http://localhost:3300/search?key=周杰伦

{
    "result": 400,
    "errMsg": "系统异常：Request failed with status code 404"
}

POST /search?key=%E5%91%A8%E6%9D%B0%E4%BC%A6 200 107.540 ms - 76
C:\Users\Administrator\Downloads\QQMusicApi\routes\search.js:83
    const {keyword} = result.data;
                             ^

TypeError: Cannot read properties of undefined (reading 'data')
    at / (C:\Users\Administrator\Downloads\QQMusicApi\routes\search.js:83:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0

**Comment by qheartq616** [comment]
search接口参考issue168修改

**Comment by qheartq616** [comment]
> [http://localhost:3300/search?key=周杰伦](http://localhost:3300/search?key=%E5%91%A8%E6%9D%B0%E4%BC%A6)
> 
> { "result": 400, "errMsg": "系统异常：Request failed with status code 404" }
> 
> POST /search?key=%E5%91%A8%E6%9D%B0%E4%BC%A6 200 107.540 ms - 76 C:\Users\Administrator\Downloads\QQMusicApi\routes\search.js:83 const {keyword} = result.data; ^
> 
> TypeError: Cannot read properties of undefined (reading 'data') at / (C:\Users\Administrator\Downloads\QQMusicApi\routes\search.js:83:30) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v18.16.0jgsijhiadsfgfgfgfsgsfgf
> > > > > 2232222


hdsfhsdf
