### ISSUE TITLE
请求没有歌词的歌曲的歌词导致崩溃

### ISSUE THREAD

**Issue by mokurin000** [jsososo/QQMusicApi#188]
`/lyric?songmid=000HETgV3jq7Cq`

```
node:internal/per_context/domexception:53
    ErrorCaptureStackTrace(this);
    ^
DOMException [InvalidCharacterError]: The string to be decoded is not correctly encoded.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at __node_internal_ (node:internal/util:505:10)
    at atob (node:buffer:1288:11)
    at _atob (/home/poly/QQMusicApi/node_modules/js-base64/base64.js:151:38)
    at _decode (/home/poly/QQMusicApi/node_modules/js-base64/base64.js:157:45)
    at Object.decode (/home/poly/QQMusicApi/node_modules/js-base64/base64.js:164:16)
    at / (/home/poly/QQMusicApi/routes/lyric.js:33:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

**Comment by qheartq616** [comment]
改一下代码嘛，没有result.lyric的时候直接返回个空就行了

**Comment by mokurin000** [comment]
> 改一下代码嘛，没有result.lyric的时候直接返回个空就行了

已经改了，但是这里好像不会再merge pr了

**Comment by qheartq616** [comment]
@poly000 是的  他说他比较忙  我还想着有人能帮我解决cookie的事情呢
