### ISSUE TITLE
设置cookie 400 无法设置

### ISSUE THREAD

**Issue by fenglindubu** [jsososo/QQMusicApi#33]
请告知 如何设置

**Comment by fenglindubu** [comment]
<!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/stylesheets/style.css"></head><body><h1>Unexpected token R in JSON at position 0</h1><h2>400</h2><pre>SyntaxError: Unexpected token R in JSON at position 0
    at JSON.parse (&lt;anonymous&gt;)
    at createStrictSyntaxError (C:\Users\Administrator\Desktop\QQMusicApi\node_modules\body-parser\lib\types\json.js:158:10)
    at parse (C:\Users\Administrator\Desktop\QQMusicApi\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\Administrator\Desktop\QQMusicApi\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\Administrator\Desktop\QQMusicApi\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\Administrator\Desktop\QQMusicApi\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\Administrator\Desktop\QQMusicApi\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)</pre></body></html>
