### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by pigger-nidoras** [jsososo/QQMusicApi#88]
https://api.qq.jsososo.com/album?albummid=002MAeob3zLXwZ
```

Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
    at /code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:635:15
    at next (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:260:14)
    at Function.handle (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:174:3)
    at router (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:47:12)
    at /code/QQMusicApi/app.js:92:3
    at Layer.handle [as handle_request] (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/layer.js:95:5)
    at trim_prefix (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:317:13)
    at /code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:284:7
    at Function.process_params (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:335:12)
    at next (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:275:10)
```

https://api.qq.jsososo.com/album/songs?albummid=002MAeob3zLXwZ
    
```
Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
    at /code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:635:15
    at next (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:260:14)
    at Function.handle (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:174:3)
    at router (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:47:12)
    at /code/QQMusicApi/app.js:92:3
    at Layer.handle [as handle_request] (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/layer.js:95:5)
    at trim_prefix (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:317:13)
    at /code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:284:7
    at Function.process_params (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:335:12)
    at next (/code/QQMusicApi/node_modules/_express@4.16.4@express/lib/router/index.js:275:10)
```

**Comment by jsososo** [comment]
服务器上有一个脏旧的文件，污染了album的接口，已修复，顺便优化了一下404报错的提示

**Comment by pigger-nidoras** [comment]
Working fine, thanks!
